import { ScrollView,StyleSheet,Text,View,Pressable } from 'react-native';
import { useEffect,useState } from 'react';
import { ALL_CHAPTERS } from '../../src/data/super50Data';
export default function DailyScreen(){
 const [hours,setHours]=useState(0),[target,setTarget]=useState(8),[questions,setQuestions]=useState({Physics:0,Chemistry:0,Math:0}),[running,setRunning]=useState(false),[seconds,setSeconds]=useState(1500),[preset,setPreset]=useState(25),[chapter,setChapter]=useState(ALL_CHAPTERS[0]?.name||'');
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setSeconds(x=>{if(x<=1){setRunning(false);setHours(h=>Math.min(target,h+preset/60));return preset*60}return x-1}),1000);return()=>clearInterval(id)},[running,preset,target]);
 const mins=Math.floor(seconds/60),secs=seconds%60,totalQ=Object.values(questions).reduce((a,b)=>a+b,0);
 const addQ=(s:'Physics'|'Chemistry'|'Math')=>setQuestions(q=>({...q,[s]:q[s]+5}));
 return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>Daily PCM Goals</Text><Text style={s.sub}>Focused study dashboard</Text>
 <View style={s.hero}><Text style={s.big}>{hours.toFixed(1)}h / {target.toFixed(1)}h</Text><Text style={s.muted}>Daily study target</Text><View style={s.bar}><View style={[s.fill,{width:Math.min(100,hours/target*100)+'%'}]} /></View><View style={s.targetRow}><Pressable onPress={()=>setTarget(Math.max(2,target-.5))}><Text style={s.step}>−0.5h</Text></Pressable><Text style={s.target}>Target {target.toFixed(1)}h</Text><Pressable onPress={()=>setTarget(Math.min(16,target+.5))}><Text style={s.step}>+0.5h</Text></Pressable></View></View>
 <View style={s.card}><Text style={s.section}>Pomodoro Focus</Text><Text style={s.timer}>{String(mins).padStart(2,'0')}:{String(secs).padStart(2,'0')}</Text><Text style={s.chapter}>Focus: {chapter}</Text><View style={s.row}>{[25,50,90].map(x=><Pressable key={x} onPress={()=>{setPreset(x);setSeconds(x*60);setRunning(false)}} style={[s.preset,preset===x&&s.presetOn]}><Text style={s.presetText}>{x}m</Text></Pressable>)}</View><Pressable style={s.start} onPress={()=>setRunning(!running)}><Text style={s.startText}>{running?'Pause':'Start Focus'}</Text></Pressable><Pressable onPress={()=>{setRunning(false);setSeconds(preset*60)}}><Text style={s.reset}>Reset timer</Text></Pressable></View>
 <View style={s.card}><Text style={s.section}>Question Practice</Text><Text style={s.questionTotal}>{totalQ} questions today</Text>{(['Physics','Chemistry','Math'] as const).map(sub=><View key={sub} style={s.qrow}><Text style={s.qname}>{sub}</Text><Text style={s.qnum}>{questions[sub]}</Text><Pressable style={s.qadd} onPress={()=>addQ(sub)}><Text style={s.qaddText}>+5</Text></Pressable></View>)}</View>
 <View style={s.card}><Text style={s.section}>Today's Chapter Focus</Text><ScrollView horizontal>{ALL_CHAPTERS.slice(0,12).map(c=><Pressable key={c.id} onPress={()=>setChapter(c.name)} style={[s.chapterPill,chapter===c.name&&s.chapterOn]}><Text style={s.pillText}>{c.name}</Text></Pressable>)}</ScrollView></View></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#050818'},content:{padding:20,paddingTop:58,paddingBottom:100},title:{color:'#F8FAFC',fontSize:30,fontWeight:'800'},sub:{color:'#94A3B8',marginTop:6,marginBottom:16},hero:{backgroundColor:'#0A1024',borderWidth:1,borderColor:'#1D3557',borderRadius:18,padding:18,marginBottom:12},big:{color:'#7DD3FC',fontSize:28,fontWeight:'900'},muted:{color:'#64748B',fontSize:11,marginTop:3},bar:{height:7,backgroundColor:'#151E35',borderRadius:8,overflow:'hidden',marginTop:15},fill:{height:'100%',backgroundColor:'#38BDF8'},targetRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:12},step:{color:'#7DD3FC',fontWeight:'800'},target:{color:'#CBD5E1',fontSize:11},card:{backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:18,padding:16,marginBottom:12},section:{color:'#F8FAFC',fontSize:15,fontWeight:'800'},timer:{color:'#FBBF24',fontSize:44,fontWeight:'900',textAlign:'center',marginTop:12},chapter:{color:'#94A3B8',fontSize:11,textAlign:'center',marginBottom:12},row:{flexDirection:'row',gap:8},preset:{flex:1,padding:10,borderRadius:10,backgroundColor:'#111A30',alignItems:'center'},presetOn:{backgroundColor:'#17324D',borderWidth:1,borderColor:'#38BDF8'},presetText:{color:'#CBD5E1',fontWeight:'700'},start:{backgroundColor:'#38BDF8',padding:13,borderRadius:11,alignItems:'center',marginTop:12},startText:{color:'#06101D',fontWeight:'900'},reset:{color:'#64748B',textAlign:'center',marginTop:10,fontSize:11},questionTotal:{color:'#FBBF24',fontSize:24,fontWeight:'900',marginVertical:10},qrow:{flexDirection:'row',alignItems:'center',paddingVertical:8,borderTopWidth:1,borderTopColor:'#182442'},qname:{color:'#CBD5E1',flex:1},qnum:{color:'#7DD3FC',fontWeight:'800',marginRight:10},qadd:{backgroundColor:'#14253A',paddingHorizontal:12,paddingVertical:7,borderRadius:8},qaddText:{color:'#7DD3FC',fontWeight:'800'},chapterPill:{backgroundColor:'#111A30',padding:9,borderRadius:9,marginRight:7},chapterOn:{backgroundColor:'#17324D',borderWidth:1,borderColor:'#38BDF8'},pillText:{color:'#CBD5E1',fontSize:10}});