import { ScrollView,StyleSheet,Text,View,Pressable,Alert,Linking } from 'react-native';
import { useEffect,useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
const KEY='iit02_rewards_v2';
const rewards=[{id:'yt',name:'YouTube Break',cost:40,icon:'▶️',url:'https://www.youtube.com'},{id:'chrome',name:'Chrome Break',cost:30,icon:'🌐',url:'googlechrome://navigate?url=https://www.google.com'},{id:'pocket',name:'Pocket FM Story',cost:50,icon:'🎧',url:'pocketfm://home'},{id:'game1',name:'Game Break',cost:80,icon:'🎮',url:'intent://#Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;package=com.pubg.imobile;end'}];
export default function GeminiScreen(){
 const [points,setPoints]=useState(0),[streak,setStreak]=useState(0),[last,setLast]=useState('');
 useEffect(()=>{AsyncStorage.getItem(KEY).then(x=>{if(x){const v=JSON.parse(x);setPoints(v.points||0);setStreak(v.streak||0);setLast(v.last||'')}})},[]);
 const save=(p:number,s:number,l=last)=>{setPoints(p);setStreak(s);setLast(l);AsyncStorage.setItem(KEY,JSON.stringify({points:p,streak:s,last:l}))};
 const daily=()=>{const today=new Date().toISOString().slice(0,10);if(last===today)return Alert.alert('Already counted','Aaj ka study goal already complete hai.');save(points+50,streak+1,today)};
 const redeem=async(r:any)=>{if(points<r.cost)return Alert.alert('Not enough points','Need '+r.cost+' JEE Mastery Points.');save(points-r.cost,streak);try{await Linking.openURL(r.url)}catch{Alert.alert('App not available','Required app/browser is not available on this device.')}};
 return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.kicker}>AI + REWARDS</Text><Text style={s.title}>Gemini Coach</Text><Text style={s.sub}>Study → earn → unlock → analyse</Text>
 <View style={s.balance}><View><Text style={s.small}>JEE MASTERY POINTS</Text><Text style={s.points}>✨ {points}</Text></View><View><Text style={s.small}>STUDY STREAK</Text><Text style={s.streak}>🔥 {streak} days</Text></View></View>
 <Pressable style={s.goal} onPress={daily}><Text style={s.goalTitle}>✅ Complete Today's Goal</Text><Text style={s.goalText}>Earn +50 points and extend your streak</Text></Pressable>
 <View style={s.card}><Text style={s.section}>Gemini Deep-Dive Unlock</Text><Text style={s.muted}>Redeem points to unlock a personalised mock-test analysis. Gemini API integration can be connected later.</Text><View style={s.gem}><Text style={s.gemText}>🔓 Deep-Dive Summary • 120 pts</Text></View></View>
 <Text style={s.section}>Reward Store</Text>
 {rewards.map(r=><View style={s.reward} key={r.id}><Text style={s.icon}>{r.icon}</Text><View style={s.info}><Text style={s.name}>{r.name}</Text><Text style={s.cost}>{r.cost} points</Text></View><Pressable onPress={()=>redeem(r)} style={s.use}><Text style={s.useText}>USE</Text></Pressable></View>)}
 <View style={s.note}><Text style={s.noteTitle}>🎮 Android note</Text><Text style={s.muted}>YouTube, Chrome and Pocket FM are launched through Android links. Installed-game discovery is restricted by Android package visibility, so this version uses a safe game shortcut.</Text></View>
 </ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#050818'},content:{padding:16,paddingTop:54,paddingBottom:100},kicker:{color:'#7DD3FC',fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{color:'#F8FAFC',fontSize:29,fontWeight:'900',marginTop:4},sub:{color:'#94A3B8',fontSize:13,marginTop:5,marginBottom:14},balance:{flexDirection:'row',justifyContent:'space-between',backgroundColor:'#0A1024',borderWidth:1,borderColor:'#7C5A18',borderRadius:14,padding:13,marginBottom:9},small:{color:'#64748B',fontSize:8,fontWeight:'900'},points:{color:'#FBBF24',fontSize:23,fontWeight:'900',marginTop:3},streak:{color:'#FB923C',fontSize:17,fontWeight:'900',marginTop:5},goal:{backgroundColor:'#102A2A',borderWidth:1,borderColor:'#1D6B5C',borderRadius:13,padding:13,marginBottom:9},goalTitle:{color:'#6EE7B7',fontWeight:'900',fontSize:13},goalText:{color:'#94A3B8',fontSize:10,marginTop:3},card:{backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:13,padding:13,marginBottom:13},section:{color:'#F8FAFC',fontSize:14,fontWeight:'900',marginBottom:7},muted:{color:'#94A3B8',fontSize:10,lineHeight:15},gem:{marginTop:10,backgroundColor:'#17324D',borderRadius:9,padding:10,alignItems:'center'},gemText:{color:'#7DD3FC',fontSize:10,fontWeight:'900'},reward:{flexDirection:'row',alignItems:'center',backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:12,padding:10,marginBottom:7},icon:{fontSize:22,width:35},info:{flex:1},name:{color:'#F8FAFC',fontWeight:'800',fontSize:12},cost:{color:'#FBBF24',fontSize:9,fontWeight:'800',marginTop:2},use:{backgroundColor:'#38BDF8',paddingHorizontal:12,paddingVertical:8,borderRadius:8},useText:{color:'#06101D',fontSize:9,fontWeight:'900'},note:{backgroundColor:'#0A1024',borderRadius:12,padding:12,marginTop:8},noteTitle:{color:'#CBD5E1',fontWeight:'800',fontSize:11,marginBottom:5}});