import { ScrollView,StyleSheet,Text,View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ALL_CHAPTERS,ALL_TESTS } from '../../src/data/super50Data';
export default function HomeScreen(){
 const p=ALL_CHAPTERS.filter(c=>c.subject==='Physics').length,c=ALL_CHAPTERS.filter(c=>c.subject==='Chemistry').length,m=ALL_CHAPTERS.filter(c=>c.subject==='Mathematics').length;
 return <ScrollView style={s.page} contentContainerStyle={s.content}>
  <Text style={s.eyebrow}>JEE 2027 • ANDROID</Text><Text style={s.title}>IIT Super-50</Text><Text style={s.subtitle}>Study. Score. Level up.</Text>
  <View style={s.hero}><View style={{flex:1}}><Text style={s.label}>TODAY'S MISSION</Text><Text style={s.heroTitle}>Complete your daily target</Text><Text style={s.heroText}>Earn JEE Mastery Points + build streak</Text></View><Text style={s.fire}>🔥</Text></View>
  <View style={s.grid}><Stat icon="flash-outline" label="Physics" value={p}/><Stat icon="flask-outline" label="Chemistry" value={c}/><Stat icon="calculator-outline" label="Maths" value={m}/><Stat icon="trophy-outline" label="Tests" value={ALL_TESTS.length}/></View>
  <View style={s.mini}><View><Text style={s.miniLabel}>🔥 STREAK</Text><Text style={s.miniValue}>Keep it alive</Text></View><View><Text style={s.miniLabel}>✨ POINTS</Text><Text style={s.miniValue}>Earn daily</Text></View><View><Text style={s.miniLabel}>🤖 GEMINI</Text><Text style={s.miniValue}>Deep-dives</Text></View></View>
  <View style={s.section}><Text style={s.sectionTitle}>5-tab command center</Text><Text style={s.sectionText}>Home • Tests • Gemini • Score • Profile</Text></View>
 </ScrollView>}
function Stat({icon,label,value}:{icon:any,label:string,value:number}){return <View style={s.card}><Ionicons name={icon} size={18} color="#7DD3FC"/><Text style={s.cardTitle}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#050818'},content:{padding:14,paddingTop:46,paddingBottom:90},eyebrow:{color:'#7DD3FC',fontSize:9,fontWeight:'900',letterSpacing:1.3},title:{color:'#F8FAFC',fontSize:29,fontWeight:'900',marginTop:3},subtitle:{color:'#94A3B8',fontSize:13,marginTop:4,marginBottom:13},hero:{backgroundColor:'#0B1430',borderWidth:1,borderColor:'#223154',borderRadius:14,padding:13,flexDirection:'row',alignItems:'center'},label:{color:'#38BDF8',fontSize:8,fontWeight:'900'},heroTitle:{color:'#F8FAFC',fontSize:16,fontWeight:'900',marginTop:5},heroText:{color:'#94A3B8',fontSize:10,marginTop:4},fire:{fontSize:31,marginLeft:8},grid:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:8},card:{backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:11,padding:9,width:'48%',minHeight:72},cardTitle:{color:'#94A3B8',fontSize:10,fontWeight:'700',marginTop:5},value:{color:'#F8FAFC',fontSize:18,fontWeight:'900',marginTop:2},mini:{flexDirection:'row',justifyContent:'space-between',backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:11,padding:10,marginTop:8},miniLabel:{color:'#64748B',fontSize:7,fontWeight:'900'},miniValue:{color:'#CBD5E1',fontSize:9,fontWeight:'800',marginTop:3},section:{marginTop:8,backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:11,padding:11},sectionTitle:{color:'#F8FAFC',fontSize:12,fontWeight:'900'},sectionText:{color:'#64748B',fontSize:10,marginTop:4}});
