import { ScrollView,StyleSheet,Text,View,Pressable } from 'react-native';
import { useState } from 'react';
const qs=[
 {q:'A body is moving with constant velocity. Its acceleration is:',o:['Zero','Constant non-zero','Increasing','Decreasing'],a:0,s:'Physics'},
 {q:'The derivative of x² with respect to x is:',o:['x','2x','x²','2'],a:1,s:'Math'},
 {q:'The pH of a neutral aqueous solution at 25°C is approximately:',o:['0','5','7','14'],a:2,s:'Chemistry'},
 {q:'If two vectors are perpendicular, their dot product is:',o:['1','0','-1','Undefined'],a:1,s:'Physics'},
 {q:'The value of sin²θ + cos²θ is:',o:['0','1','2','sinθ'],a:1,s:'Math'},
 {q:'Avogadro number is approximately:',o:['6.022×10²³','9.8','3×10⁸','1.6×10⁻¹⁹'],a:0,s:'Chemistry'}
];
export default function QuizScreen(){const [i,setI]=useState(0),[score,setScore]=useState(0),[picked,setPicked]=useState<number|null>(null),[done,setDone]=useState(false);const q=qs[i];const answer=(x:number)=>{if(picked!==null)return;setPicked(x);if(x===q.a)setScore(s=>s+1)};const next=()=>{if(i===qs.length-1)setDone(true);else{setI(x=>x+1);setPicked(null)}};if(done)return <View style={s.done}><Text style={s.emoji}>🏆</Text><Text style={s.title}>Quiz Complete</Text><Text style={s.score}>{score} / {qs.length}</Text><Text style={s.sub}>Accuracy: {Math.round(score/qs.length*100)}%</Text><Pressable style={s.btn} onPress={()=>{setI(0);setScore(0);setPicked(null);setDone(false)}}><Text style={s.btnText}>Retry Quiz</Text></Pressable></View>;return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>AI Quiz</Text><Text style={s.sub}>Offline practice • Physics • Chemistry • Mathematics</Text><View style={s.progress}><View style={[s.fill,{width:((i+1)/qs.length*100)+'%'}]}/></View><Text style={s.counter}>Question {i+1} / {qs.length} • {q.s}</Text><View style={s.card}><Text style={s.question}>{q.q}</Text>{q.o.map((x,n)=><Pressable key={x} onPress={()=>answer(n)} style={[s.option,picked===n&&n===q.a&&s.correct,picked===n&&n!==q.a&&s.wrong]}><Text style={s.optText}>{String.fromCharCode(65+n)}. {x}</Text></Pressable>)}{picked!==null&&<Text style={[s.feedback,picked===q.a?s.good:s.bad]}>{picked===q.a?'✓ Correct':'✗ Incorrect'}</Text>}<Pressable disabled={picked===null} onPress={next} style={[s.btn,picked===null&&s.disabled]}><Text style={s.btnText}>{i===qs.length-1?'Finish':'Next Question'}</Text></Pressable></View></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#050818'},content:{padding:20,paddingTop:58,paddingBottom:100},title:{color:'#F8FAFC',fontSize:30,fontWeight:'800'},sub:{color:'#94A3B8',marginTop:6,marginBottom:16},progress:{height:6,backgroundColor:'#151E35',borderRadius:8,overflow:'hidden'},fill:{height:'100%',backgroundColor:'#38BDF8'},counter:{color:'#7DD3FC',fontSize:11,fontWeight:'800',marginVertical:14},card:{backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:18,padding:17},question:{color:'#F8FAFC',fontSize:19,fontWeight:'800',lineHeight:27,marginBottom:14},option:{backgroundColor:'#111A30',borderWidth:1,borderColor:'#24304A',borderRadius:11,padding:13,marginBottom:8},correct:{borderColor:'#22C55E',backgroundColor:'#0B2A20'},wrong:{borderColor:'#EF4444',backgroundColor:'#30151A'},optText:{color:'#CBD5E1',fontSize:12},feedback:{fontWeight:'900',marginVertical:8},good:{color:'#4ADE80'},bad:{color:'#FB7185'},btn:{backgroundColor:'#38BDF8',padding:13,borderRadius:11,alignItems:'center',marginTop:12},disabled:{opacity:.35},btnText:{color:'#06101D',fontWeight:'900'},done:{flex:1,backgroundColor:'#050818',alignItems:'center',justifyContent:'center',padding:30},emoji:{fontSize:55},score:{color:'#FBBF24',fontSize:44,fontWeight:'900',marginTop:10},feedback:{fontWeight:'900',marginVertical:8},good:{color:'#4ADE80'},bad:{color:'#FB7185}});
