import { ScrollView,StyleSheet,Text,View,Pressable,TextInput } from 'react-native';
import { useState } from 'react';
import { ALL_TESTS,ALL_CHAPTERS } from '../../src/data/super50Data';
export default function ScoresScreen(){
 const [results,setResults]=useState<any[]>([]),[open,setOpen]=useState(false),[testId,setTestId]=useState(ALL_TESTS[0]?.id||''),[p,setP]=useState('0'),[c,setC]=useState('0'),[m,setM]=useState('0'),[max,setMax]=useState('300'),[acc,setAcc]=useState('85'),[mist,setMist]=useState('3'),[notes,setNotes]=useState(''),[weak,setWeak]=useState<string[]>([]);
 const test=ALL_TESTS.find(t=>t.id===testId),total=+p + +c + +m,pct=+max?Math.round(total/+max*100):0;
 const toggle=(id:string)=>setWeak(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);
 const save=()=>{setResults(r=>[{id:Date.now(),testName:test?.name||'Test',date:new Date().toISOString().slice(0,10),p:+p,c:+c,m:+m,max:+max,acc:+acc,mist:+mist,weak,notes},...r]);setOpen(false);setWeak([]);setNotes('');};
 return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>Score Tracker</Text><Text style={s.sub}>Mock test scorecard • mistakes • weak chapters</Text>
 <View style={s.stats}><Stat l="Tests" v={String(results.length)}/><Stat l="Best %" v={results.length?Math.max(...results.map(x=>Math.round((x.p+x.c+x.m)/x.max*100)))+'%':'—'}/><Stat l="Avg Accuracy" v={results.length?Math.round(results.reduce((a,x)=>a+x.acc,0)/results.length)+'%':'—'}/></View>
 <Pressable style={s.add} onPress={()=>setOpen(!open)}><Text style={s.addText}>{open?'Close Logger':'＋ Log New Test Score'}</Text></Pressable>
 {open&&<View style={s.form}><Text style={s.formTitle}>Record Mock Test Performance</Text><Text style={s.label}>Test</Text><ScrollView horizontal>{ALL_TESTS.map(t=><Pressable key={t.id} onPress={()=>setTestId(t.id)} style={[s.pill,testId===t.id&&s.sel]}><Text style={s.pillText}>{t.name}</Text></Pressable>)}</ScrollView>
 <View style={s.row}>{[['Physics',p,setP],['Chemistry',c,setC],['Math',m,setM],['Max',max,setMax]].map(([l,v,set])=><View style={s.box} key={String(l)}><Text style={s.label}>{l as string}</Text><TextInput keyboardType="numeric" value={v as string} onChangeText={set as any} style={s.input}/></View>)}</View>
 <View style={s.total}><Text style={s.totalText}>{total} / {max} • {pct}%</Text></View>
 <View style={s.row}>{[['Accuracy %',acc,setAcc],['Silly mistakes',mist,setMist]].map(([l,v,set])=><View style={s.box} key={String(l)}><Text style={s.label}>{l as string}</Text><TextInput keyboardType="numeric" value={v as string} onChangeText={set as any} style={s.input}/></View>)}</View>
 <Text style={s.label}>Weak chapters</Text><View style={s.wrap}>{ALL_CHAPTERS.map(ch=><Pressable key={ch.id} onPress={()=>toggle(ch.id)} style={[s.weak,weak.includes(ch.id)&&s.weakOn]}><Text style={s.weakText}>{ch.name}</Text></Pressable>)}</View>
 <Text style={s.label}>Analysis / learnings</Text><TextInput multiline value={notes} onChangeText={setNotes} placeholder="Formula gaps, speed issues, mistakes..." placeholderTextColor="#64748B" style={[s.input,s.notes]}/><Pressable style={s.save} onPress={save}><Text style={s.saveText}>Save Scorecard</Text></Pressable></View>}
 {results.map(r=><View key={r.id} style={s.card}><Text style={s.name}>{r.testName} • {r.date}</Text><Text style={s.score}>{r.p+r.c+r.m} / {r.max} ({Math.round((r.p+r.c+r.m)/r.max*100)}%)</Text><Text style={s.meta}>P {r.p} • C {r.c} • M {r.m} • Accuracy {r.acc}% • Mistakes {r.mist}</Text>{r.weak.length>0&&<Text style={s.weakLine}>Weak: {r.weak.map((id:string)=>ALL_CHAPTERS.find(x=>x.id===id)?.name).filter(Boolean).join(', ')}</Text>}{r.notes?<Text style={s.notesLine}>{r.notes}</Text>:null}</View>)}</ScrollView>}
function Stat({l,v}:{l:string,v:string}){return <View style={s.stat}><Text style={s.statValue}>{v}</Text><Text style={s.statLabel}>{l}</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#050818'},content:{padding:20,paddingTop:58,paddingBottom:100},title:{color:'#F8FAFC',fontSize:30,fontWeight:'800'},sub:{color:'#94A3B8',marginTop:7,marginBottom:16},stats:{flexDirection:'row',gap:8,marginBottom:12},stat:{flex:1,backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:15,padding:12},statValue:{color:'#F8FAFC',fontSize:19,fontWeight:'800'},statLabel:{color:'#64748B',fontSize:10,marginTop:3},add:{backgroundColor:'#FBBF24',padding:13,borderRadius:13,alignItems:'center',marginBottom:12},addText:{color:'#080D20',fontWeight:'800'},form:{backgroundColor:'#0A1024',borderWidth:1,borderColor:'#24304A',borderRadius:17,padding:14,marginBottom:14},formTitle:{color:'#fff',fontWeight:'800',fontSize:16,marginBottom:12},label:{color:'#94A3B8',fontSize:10,fontWeight:'700',marginBottom:5,marginTop:8},row:{flexDirection:'row',gap:7},box:{flex:1},input:{backgroundColor:'#070D1D',borderWidth:1,borderColor:'#24304A',borderRadius:9,color:'#fff',paddingHorizontal:10,paddingVertical:9},pill:{padding:9,backgroundColor:'#111A30',borderRadius:9,marginRight:6},sel:{backgroundColor:'#17324D',borderWidth:1,borderColor:'#38BDF8'},pillText:{color:'#CBD5E1',fontSize:10},total:{marginTop:10,padding:12,borderRadius:10,backgroundColor:'#101A2D',alignItems:'center'},totalText:{color:'#FBBF24',fontWeight:'800',fontSize:16},wrap:{flexDirection:'row',flexWrap:'wrap',gap:5},weak:{padding:7,borderRadius:8,backgroundColor:'#111A30'},weakOn:{backgroundColor:'#3A1720',borderWidth:1,borderColor:'#9F1239'},weakText:{color:'#CBD5E1',fontSize:9},notes:{minHeight:75,textAlignVertical:'top'},save:{backgroundColor:'#38BDF8',padding:12,borderRadius:10,alignItems:'center',marginTop:12},saveText:{color:'#06101D',fontWeight:'800'},card:{backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:16,padding:14,marginBottom:10},name:{color:'#fff',fontWeight:'800'},score:{color:'#FBBF24',fontSize:21,fontWeight:'900',marginTop:7},meta:{color:'#94A3B8',fontSize:10,marginTop:5},weakLine:{color:'#FDA4AF',fontSize:10,marginTop:6},notesLine:{color:'#CBD5E1',fontSize:10,marginTop:6}});
