import { ScrollView,StyleSheet,Text,View,Pressable } from 'react-native';
import { useState } from 'react';
import { ALL_CHAPTERS,ALL_TESTS } from '../../src/data/super50Data';
export default function StrategyScreen(){
 const [correct,setCorrect]=useState(52),[wrong,setWrong]=useState(10); const score=correct*4-wrong,acc=correct+wrong?Math.round(correct/(correct+wrong)*100):0; const next=ALL_TESTS.find(t=>t.date>=new Date().toISOString().slice(0,10))||ALL_TESTS[0];
 return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.title}>Strategy Coach</Text><Text style={s.sub}>Test readiness • study balance • negative-marking calculator</Text>
 <View style={s.card}><Text style={s.kicker}>UPCOMING TEST</Text><Text style={s.name}>{next?.name||'JEE Test'}</Text><Text style={s.muted}>{next?.date} • {next?.mode}</Text></View>
 <View style={s.card}><Text style={s.section}>Negative Marking Calculator</Text><Text style={s.big}>{score} marks</Text><Text style={s.muted}>Accuracy {acc}% • Correct {correct} • Wrong {wrong}</Text><View style={s.row}><Stepper label='Correct' value={correct} set={setCorrect}/><Stepper label='Wrong' value={wrong} set={setWrong}/></View></View>
 <View style={s.card}><Text style={s.section}>7-Day Strategy</Text><Tip n='1' h='Concept Builder' d='Weak chapters ki theory + 1-page summary complete karo.'/><Tip n='2' h='Problem Solving' d='MathonGo PYQ aur Module Ex-2 ko timed practice mein karo.'/><Tip n='3' h='Test Simulation' d='Upcoming test se pehle full timed paper + mistake analysis karo.'/><Tip n='4' h='Revision' d='Formula sheets aur previously wrong questions ko daily revise karo.'/></View>
 <View style={s.card}><Text style={s.section}>Quick Focus Split</Text><Text style={s.split}>Physics  •  2.5h</Text><Text style={s.split}>Chemistry • 2.5h</Text><Text style={s.split}>Mathematics • 2.5h</Text></View></ScrollView>}
function Stepper({label,value,set}:{label:string,value:number,set:(x:number)=>void}){return <View style={s.step}><Text style={s.label}>{label}</Text><View style={s.stepRow}><Pressable onPress={()=>set(Math.max(0,value-1))}><Text style={s.control}>−</Text></Pressable><Text style={s.val}>{value}</Text><Pressable onPress={()=>set(value+1)}><Text style={s.control}>+</Text></Pressable></View></View>}
function Tip({n,h,d}:{n:string,h:string,d:string}){return <View style={s.tip}><Text style={s.num}>{n}</Text><View style={{flex:1}}><Text style={s.tipHead}>{h}</Text><Text style={s.muted}>{d}</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#050818'},content:{padding:20,paddingTop:58,paddingBottom:100},title:{color:'#F8FAFC',fontSize:30,fontWeight:'800'},sub:{color:'#94A3B8',marginTop:6,marginBottom:16},card:{backgroundColor:'#0A1024',borderWidth:1,borderColor:'#182442',borderRadius:18,padding:16,marginBottom:12},kicker:{color:'#7DD3FC',fontSize:9,fontWeight:'900'},name:{color:'#fff',fontSize:18,fontWeight:'900',marginTop:5},muted:{color:'#94A3B8',fontSize:10,lineHeight:15,marginTop:3},section:{color:'#F8FAFC',fontSize:15,fontWeight:'800'},big:{color:'#FBBF24',fontSize:32,fontWeight:'900',marginTop:10},row:{flexDirection:'row',gap:12,marginTop:12},step:{flex:1,backgroundColor:'#070D1D',borderRadius:10,padding:10},label:{color:'#64748B',fontSize:9,fontWeight:'800'},stepRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:5},control:{color:'#7DD3FC',fontSize:20,fontWeight:'900'},val:{color:'#fff',fontWeight:'900'},tip:{flexDirection:'row',gap:10,marginTop:14},num:{color:'#050818',backgroundColor:'#38BDF8',width:24,height:24,textAlign:'center',paddingTop:4,borderRadius:12,fontWeight:'900'},tipHead:{color:'#F8FAFC',fontWeight:'800',fontSize:12},split:{color:'#CBD5E1',fontSize:12,fontWeight:'700',paddingVertical:5}});